version: "3.8"

x-common: &common
  networks:
    - default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  minio:
    image: docker.io/bitnami/minio:2024
    container_name: minio
    hostname: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/bitnami/minio
    <<: *common

  redis:
    image: bitnami/redis:7.2.5
    container_name: redis
    hostname: redis
    volumes:
      - redis_data:/bitnami/redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-phantombe}
    ports:
      - 6379:6379
    <<: *common

volumes:
  minio_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    driver: bridge
