x-common: &common
  networks:
    - default
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  minio:
    image: docker.io/bitnami/minio:2024
    container_name: minio
    hostname: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/bitnami/minio
    <<: *common

  redis:
    image: bitnami/redis:7.2.5
    container_name: redis
    hostname: redis
    volumes:
      - redis_data:/bitnami/redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redisadmin}
    ports:
      - 6379:6379
    <<: *common

  postgres:
    image: postgres:17
    container_name: postgres
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: xgist
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    <<: *common

  keycloak_db:
    image: postgres:17
    container_name: keycloak_db
    hostname: keycloak_db
    volumes:
      - keycloak_data:/var/lib/keycloak/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 6543:5432
    <<: *common

  keycloak:
    image: quay.io/phasetwo/phasetwo-keycloak:latest
    container_name: keycloak
    hostname: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_LOG_LEVEL: INFO
    command: start-dev
    ports:
      - 8084:8080
      - 8443:8443
    depends_on:
      - postgres
    <<: *common

volumes:
  minio_data:
    driver: local
  redis_data:
    driver: local
  postgres_data:
    driver: local
  keycloak_data:
    driver: local

networks:
  default:
    driver: bridge
