// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AudioJob struct {
	ID         string  `json:"id"`
	Kind       string  `json:"kind"`
	Status     string  `json:"status"`
	InputText  string  `json:"inputText"`
	OutputText *string `json:"outputText,omitempty"`
	Voice      *string `json:"voice,omitempty"`
	DurationMs *int    `json:"durationMs,omitempty"`
	URL        *string `json:"url,omitempty"`
	ErrorCode  *string `json:"errorCode,omitempty"`
	CreatedAt  string  `json:"createdAt"`
}

type AudioJobPage struct {
	Items      []AudioJob `json:"items"`
	NextCursor *string    `json:"nextCursor,omitempty"`
}

type AuthPayload struct {
	User         *User  `json:"user"`
	SessionToken string `json:"sessionToken"`
	ExpiresAt    string `json:"expiresAt"`
}

type BillingSubscription struct {
	ID          string             `json:"id"`
	Plan        string             `json:"plan"`
	Status      SubscriptionStatus `json:"status"`
	PeriodStart string             `json:"periodStart"`
	PeriodEnd   string             `json:"periodEnd"`
}

type BillingSummary struct {
	AvailableCredits int                  `json:"availableCredits"`
	ReservedCredits  int                  `json:"reservedCredits"`
	Subscription     *BillingSubscription `json:"subscription,omitempty"`
}

type CheckoutSession struct {
	CheckoutURL string `json:"checkoutUrl"`
}

type Content struct {
	MediaID       string         `json:"mediaId"`
	Transcript    *Transcript    `json:"transcript,omitempty"`
	Summaries     []Summary      `json:"summaries"`
	Keywords      []Keyword      `json:"keywords"`
	Keypoints     []Keypoint     `json:"keypoints"`
	Notes         []Note         `json:"notes"`
	SummaryAudios []SummaryAudio `json:"summaryAudios"`
	Version       int            `json:"version"`
}

type CreditLedgerEntry struct {
	ID        string  `json:"id"`
	Delta     int     `json:"delta"`
	EntryType string  `json:"entryType"`
	ItemID    *string `json:"itemId,omitempty"`
	CreatedAt string  `json:"createdAt"`
}

type CreditLedgerPage struct {
	Items      []CreditLedgerEntry `json:"items"`
	NextCursor *string             `json:"nextCursor,omitempty"`
}

type CreditPack struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Description   *string `json:"description,omitempty"`
	Credits       int     `json:"credits"`
	PriceAmount   int     `json:"priceAmount"`
	PriceCurrency *string `json:"priceCurrency,omitempty"`
}

type DeletionOperation struct {
	DeletionID  string        `json:"deletionId"`
	UserID      string        `json:"userId"`
	State       DeletionState `json:"state"`
	CreatedAt   string        `json:"createdAt"`
	CompletedAt *string       `json:"completedAt,omitempty"`
}

type Keypoint struct {
	PointIndex   int    `json:"pointIndex"`
	Text         string `json:"text"`
	StartSegment int    `json:"startSegment"`
	EndSegment   int    `json:"endSegment"`
}

type Keyword struct {
	Keyword  string  `json:"keyword"`
	Score    float64 `json:"score"`
	Position int     `json:"position"`
}

type Media struct {
	ID           string      `json:"id"`
	Title        string      `json:"title"`
	MediaType    MediaType   `json:"mediaType"`
	MimeType     string      `json:"mimeType"`
	SizeBytes    int         `json:"sizeBytes"`
	DurationMs   int         `json:"durationMs"`
	Status       MediaStatus `json:"status"`
	ThumbnailURL *string     `json:"thumbnailUrl,omitempty"`
	CreatedAt    string      `json:"createdAt"`
	UpdatedAt    string      `json:"updatedAt"`
	Description  *string     `json:"description,omitempty"`
	TrashedAt    *string     `json:"trashedAt,omitempty"`
}

type MediaDetail struct {
	ID                   string      `json:"id"`
	Title                string      `json:"title"`
	MediaType            MediaType   `json:"mediaType"`
	MimeType             string      `json:"mimeType"`
	SizeBytes            int         `json:"sizeBytes"`
	DurationMs           int         `json:"durationMs"`
	Status               MediaStatus `json:"status"`
	ThumbnailURL         *string     `json:"thumbnailUrl,omitempty"`
	PlaybackURL          *string     `json:"playbackUrl,omitempty"`
	PlaybackURLExpiresAt *string     `json:"playbackUrlExpiresAt,omitempty"`
	CreatedAt            string      `json:"createdAt"`
	UpdatedAt            string      `json:"updatedAt"`
	Description          *string     `json:"description,omitempty"`
}

type MediaPage struct {
	Items      []Media `json:"items"`
	NextCursor *string `json:"nextCursor,omitempty"`
}

type MediaProgress struct {
	MediaID          string           `json:"mediaId"`
	Status           MediaStatus      `json:"status"`
	ProcessingStatus ProcessingStatus `json:"processingStatus"`
	CompletedSteps   int              `json:"completedSteps"`
	TotalSteps       int              `json:"totalSteps"`
	UpdatedAt        string           `json:"updatedAt"`
	Version          int              `json:"version"`
}

type Mutation struct {
}

type Note struct {
	Format    string `json:"format"`
	Body      string `json:"body"`
	CreatedAt string `json:"createdAt"`
}

type Plan struct {
	ID                string   `json:"id"`
	Name              string   `json:"name"`
	Description       *string  `json:"description,omitempty"`
	PriceAmount       int      `json:"priceAmount"`
	PriceCurrency     *string  `json:"priceCurrency,omitempty"`
	RecurringInterval string   `json:"recurringInterval"`
	Benefits          []string `json:"benefits"`
}

type PriceCatalog struct {
	CatalogVersion string      `json:"catalogVersion"`
	Items          []QuoteItem `json:"items"`
}

type PromptSetting struct {
	Section    string `json:"section"`
	PromptText string `json:"promptText"`
	UpdatedAt  string `json:"updatedAt"`
}

type Query struct {
}

type Quote struct {
	ID             string      `json:"id"`
	CatalogVersion string      `json:"catalogVersion"`
	Items          []QuoteItem `json:"items"`
	TotalCredits   int         `json:"totalCredits"`
	ExpiresAt      string      `json:"expiresAt"`
}

type QuoteItem struct {
	ItemID  string `json:"itemId"`
	Credits int    `json:"credits"`
}

type Summary struct {
	SummaryType   string            `json:"summaryType"`
	Text          string            `json:"text"`
	Model         string            `json:"model"`
	PromptVersion string            `json:"promptVersion"`
	Sentences     []SummarySentence `json:"sentences"`
	CreatedAt     string            `json:"createdAt"`
}

type SummaryAudio struct {
	SummaryType string             `json:"summaryType"`
	MimeType    string             `json:"mimeType"`
	DurationMs  int                `json:"durationMs"`
	Voice       string             `json:"voice"`
	Status      SummaryAudioStatus `json:"status"`
	URL         *string            `json:"url,omitempty"`
}

type SummarySentence struct {
	SentenceIndex       int    `json:"sentenceIndex"`
	Text                string `json:"text"`
	CitedSegmentIndexes []int  `json:"citedSegmentIndexes"`
}

type ThumbnailUpload struct {
	ObjectKey string `json:"objectKey"`
	UploadURL string `json:"uploadUrl"`
	ExpiresAt string `json:"expiresAt"`
}

type Transcript struct {
	Language string              `json:"language"`
	Text     string              `json:"text"`
	Segments []TranscriptSegment `json:"segments"`
}

type TranscriptSegment struct {
	SegmentIndex int     `json:"segmentIndex"`
	StartMs      int     `json:"startMs"`
	EndMs        int     `json:"endMs"`
	Speaker      *string `json:"speaker,omitempty"`
	Text         string  `json:"text"`
}

type UploadSession struct {
	ID        string `json:"id"`
	MediaID   string `json:"mediaId"`
	UploadURL string `json:"uploadUrl"`
	Status    string `json:"status"`
	ExpiresAt string `json:"expiresAt"`
}

type User struct {
	ID            string       `json:"id"`
	Email         string       `json:"email"`
	Name          string       `json:"name"`
	ImageURL      *string      `json:"imageUrl,omitempty"`
	EmailVerified bool         `json:"emailVerified"`
	State         AccountState `json:"state"`
	CreatedAt     string       `json:"createdAt"`
}

type AccountState string

const (
	AccountStateActive          AccountState = "ACTIVE"
	AccountStateDeletionPending AccountState = "DELETION_PENDING"
	AccountStateTombstoned      AccountState = "TOMBSTONED"
)

var AllAccountState = []AccountState{
	AccountStateActive,
	AccountStateDeletionPending,
	AccountStateTombstoned,
}

func (e AccountState) IsValid() bool {
	switch e {
	case AccountStateActive, AccountStateDeletionPending, AccountStateTombstoned:
		return true
	}
	return false
}

func (e AccountState) String() string {
	return string(e)
}

func (e *AccountState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccountState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccountState", str)
	}
	return nil
}

func (e AccountState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccountState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccountState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DeletionState string

const (
	DeletionStatePending                 DeletionState = "PENDING"
	DeletionStateCompleted               DeletionState = "COMPLETED"
	DeletionStateFailedAttentionRequired DeletionState = "FAILED_ATTENTION_REQUIRED"
)

var AllDeletionState = []DeletionState{
	DeletionStatePending,
	DeletionStateCompleted,
	DeletionStateFailedAttentionRequired,
}

func (e DeletionState) IsValid() bool {
	switch e {
	case DeletionStatePending, DeletionStateCompleted, DeletionStateFailedAttentionRequired:
		return true
	}
	return false
}

func (e DeletionState) String() string {
	return string(e)
}

func (e *DeletionState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DeletionState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DeletionState", str)
	}
	return nil
}

func (e DeletionState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DeletionState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DeletionState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MediaStatus string

const (
	MediaStatusPendingUpload   MediaStatus = "PENDING_UPLOAD"
	MediaStatusProcessing      MediaStatus = "PROCESSING"
	MediaStatusCompleted       MediaStatus = "COMPLETED"
	MediaStatusFailed          MediaStatus = "FAILED"
	MediaStatusDeletionPending MediaStatus = "DELETION_PENDING"
)

var AllMediaStatus = []MediaStatus{
	MediaStatusPendingUpload,
	MediaStatusProcessing,
	MediaStatusCompleted,
	MediaStatusFailed,
	MediaStatusDeletionPending,
}

func (e MediaStatus) IsValid() bool {
	switch e {
	case MediaStatusPendingUpload, MediaStatusProcessing, MediaStatusCompleted, MediaStatusFailed, MediaStatusDeletionPending:
		return true
	}
	return false
}

func (e MediaStatus) String() string {
	return string(e)
}

func (e *MediaStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MediaStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MediaStatus", str)
	}
	return nil
}

func (e MediaStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MediaStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MediaStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MediaType string

const (
	MediaTypeAudio MediaType = "AUDIO"
	MediaTypeVideo MediaType = "VIDEO"
)

var AllMediaType = []MediaType{
	MediaTypeAudio,
	MediaTypeVideo,
}

func (e MediaType) IsValid() bool {
	switch e {
	case MediaTypeAudio, MediaTypeVideo:
		return true
	}
	return false
}

func (e MediaType) String() string {
	return string(e)
}

func (e *MediaType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MediaType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MediaType", str)
	}
	return nil
}

func (e MediaType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MediaType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MediaType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProcessingStatus string

const (
	ProcessingStatusUnspecified ProcessingStatus = "UNSPECIFIED"
	ProcessingStatusRequested   ProcessingStatus = "REQUESTED"
	ProcessingStatusAccepted    ProcessingStatus = "ACCEPTED"
	ProcessingStatusCompleted   ProcessingStatus = "COMPLETED"
	ProcessingStatusFailed      ProcessingStatus = "FAILED"
)

var AllProcessingStatus = []ProcessingStatus{
	ProcessingStatusUnspecified,
	ProcessingStatusRequested,
	ProcessingStatusAccepted,
	ProcessingStatusCompleted,
	ProcessingStatusFailed,
}

func (e ProcessingStatus) IsValid() bool {
	switch e {
	case ProcessingStatusUnspecified, ProcessingStatusRequested, ProcessingStatusAccepted, ProcessingStatusCompleted, ProcessingStatusFailed:
		return true
	}
	return false
}

func (e ProcessingStatus) String() string {
	return string(e)
}

func (e *ProcessingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProcessingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProcessingStatus", str)
	}
	return nil
}

func (e ProcessingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProcessingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProcessingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusNone     SubscriptionStatus = "NONE"
	SubscriptionStatusActive   SubscriptionStatus = "ACTIVE"
	SubscriptionStatusCanceled SubscriptionStatus = "CANCELED"
	SubscriptionStatusPastDue  SubscriptionStatus = "PAST_DUE"
)

var AllSubscriptionStatus = []SubscriptionStatus{
	SubscriptionStatusNone,
	SubscriptionStatusActive,
	SubscriptionStatusCanceled,
	SubscriptionStatusPastDue,
}

func (e SubscriptionStatus) IsValid() bool {
	switch e {
	case SubscriptionStatusNone, SubscriptionStatusActive, SubscriptionStatusCanceled, SubscriptionStatusPastDue:
		return true
	}
	return false
}

func (e SubscriptionStatus) String() string {
	return string(e)
}

func (e *SubscriptionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SubscriptionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SubscriptionStatus", str)
	}
	return nil
}

func (e SubscriptionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SubscriptionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SubscriptionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SummaryAudioStatus string

const (
	SummaryAudioStatusReady  SummaryAudioStatus = "READY"
	SummaryAudioStatusFailed SummaryAudioStatus = "FAILED"
)

var AllSummaryAudioStatus = []SummaryAudioStatus{
	SummaryAudioStatusReady,
	SummaryAudioStatusFailed,
}

func (e SummaryAudioStatus) IsValid() bool {
	switch e {
	case SummaryAudioStatusReady, SummaryAudioStatusFailed:
		return true
	}
	return false
}

func (e SummaryAudioStatus) String() string {
	return string(e)
}

func (e *SummaryAudioStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SummaryAudioStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SummaryAudioStatus", str)
	}
	return nil
}

func (e SummaryAudioStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SummaryAudioStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SummaryAudioStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
