CREATE TABLE workflows (
  id uuid PRIMARY KEY,
  media_id uuid NOT NULL UNIQUE,
  request_id uuid NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  state text NOT NULL,
  quote_id uuid NOT NULL,
  version bigint NOT NULL DEFAULT 0,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE TABLE workflow_steps (
  id uuid PRIMARY KEY,
  workflow_id uuid NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
  step_type text NOT NULL,
  required boolean NOT NULL,
  state text NOT NULL,
  current_attempt integer NOT NULL DEFAULT 0,
  deadline_at timestamptz,
  UNIQUE (workflow_id, step_type)
);
CREATE INDEX workflow_steps_dispatched_deadline ON workflow_steps (deadline_at) WHERE state = 'dispatched';

CREATE TABLE step_dependencies (
  step_id uuid NOT NULL REFERENCES workflow_steps(id) ON DELETE CASCADE,
  depends_on_step_id uuid NOT NULL REFERENCES workflow_steps(id) ON DELETE CASCADE,
  PRIMARY KEY (step_id, depends_on_step_id),
  CHECK (step_id <> depends_on_step_id)
);

-- step_attempts.idempotency_key is deterministic ("<step_id>:<attempt>"),
-- generated by dispatchStep, so it doubles as the natural per-attempt
-- unique key worker.md's handlers dedupe against.
CREATE TABLE step_attempts (
  id uuid PRIMARY KEY,
  step_id uuid NOT NULL REFERENCES workflow_steps(id) ON DELETE CASCADE,
  attempt integer NOT NULL,
  idempotency_key text NOT NULL UNIQUE,
  state text NOT NULL,
  error_code text,
  retry_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  UNIQUE (step_id, attempt)
);
CREATE INDEX step_attempts_due_retries ON step_attempts (retry_at) WHERE state = 'retry_scheduled';

-- deletion_operations is conductor's tombstone for its participant role
-- in media's per-media deletion flow (ADR 0006): it lets a redelivered or
-- reconciler-republished mn.media.deletion.requested.v1 be a no-op after
-- the first successful cancellation, even for a media item that never had
-- a workflow (e.g. deleted before its upload was confirmed).
CREATE TABLE deletion_operations (
  deletion_id uuid PRIMARY KEY,
  media_id uuid NOT NULL,
  state text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE TABLE inbox_events (
  event_id uuid PRIMARY KEY,
  topic text NOT NULL,
  processed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE outbox_events (
  id uuid PRIMARY KEY,
  topic text NOT NULL,
  event_key text NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz,
  attempts integer NOT NULL DEFAULT 0
);
CREATE INDEX outbox_events_pending ON outbox_events (created_at) WHERE published_at IS NULL;
