name: Deploy Server

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/ci_server.yml"
      - ".github/workflows/_reusable-deploy.yml"
      - "apps/server/**"
      - "packages/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: ./.github/workflows/_reusable-deploy.yml
    with:
      app-name: server
      context: .
      dockerfile: ./apps/server/Dockerfile
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CAPROVER_SERVER: ${{ secrets.CAPROVER_SERVER }}
      CAPROVER_APP_NAME: ${{ secrets.SERVER_APP_NAME }}
      CAPROVER_APP_TOKEN: ${{ secrets.SERVER_APP_TOKEN }}