name: Deploy Worker

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/ci_worker.yml"
      - ".github/workflows/_reusable-deploy.yml"
      - "apps/worker/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: ./.github/workflows/_reusable-deploy.yml
    with:
      app-name: worker
      context: ./apps/worker
      dockerfile: ./apps/worker/Dockerfile
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CAPROVER_SERVER: ${{ secrets.CAPROVER_SERVER }}
      CAPROVER_APP_NAME: ${{ secrets.WORKER_APP_NAME }}
      CAPROVER_APP_TOKEN: ${{ secrets.WORKER_APP_TOKEN }}