name: Build and deploy Web Service

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/ci_web.yml"
      - "apps/web/**"

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Preset Image Name
        run: |
          IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/web:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV
      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/web
          file: ./apps/web/Dockerfile
          push: true
          tags: ${{ env.IMAGE_URL }}
          build-args: |
            VITE_KEYCLOAK_URL=${{ vars.VITE_KEYCLOAK_URL }}
            VITE_KEYCLOAK_REALM=${{ vars.VITE_KEYCLOAK_REALM }}
            VITE_CLIENT_ID=${{ vars.VITE_CLIENT_ID }}
            VITE_BASE_URL=${{ vars.VITE_BASE_URL }}
      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.WEB_APP_NAME }}"
          token: "${{ secrets.WEB_APP_TOKEN }}"
          image: ${{ env.IMAGE_URL }}
