name: Deploy Web

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/ci_web.yml"
      - ".github/workflows/_reusable-deploy.yml"
      - "apps/web/**"
      - "packages/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: ./.github/workflows/_reusable-deploy.yml
    with:
      app-name: web
      context: .
      dockerfile: ./apps/web/Dockerfile
      build-args: |
        VITE_BASE_URL=${{ vars.VITE_BASE_URL }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CAPROVER_SERVER: ${{ secrets.CAPROVER_SERVER }}
      CAPROVER_APP_NAME: ${{ secrets.WEB_APP_NAME }}
      CAPROVER_APP_TOKEN: ${{ secrets.WEB_APP_TOKEN }}